name: RedSkyBlock
author: RedCraftPE
version: 0.0.1
api: 3.0.0
main: RedCraftPE\RedSkyBlock\SkyBlock
commands:
  island:
    description: This is the main command for RedSkyBlock.
    aliases: [is, isle, sb, skyblock]
    usage: /island <args>
  spawn:
    description: This command will take the user to the server spawn.
    usage: /spawn
permissions:
    skyblock.create:
      description: With this permission players can create a SkyBlock island.
      default: true
    skyblock.createworld:
      description: With this permission players can create and set a SkyBlock world for the server.
      default: op
    skyblock.lock:
      description: With this permission players can lock/unlock their skyblock island.
      default: true
    skyblock.members:
      description: With this permission players can add/remove members from their skyblock island.
      default: true
    skyblock.setspawn:
      description: With this permission players can set the spawn on their skyblock island.
      default: true
    skyblock.setworld:
      description: With this permission players can set the SkyBlock world of a server.
      default: op
    skyblock.tp:
      description: With this permission players can teleport to other player's islands.
      default: true
    skyblock.updatezone:
      description: With this permission players can update the Island Zone.
      default: op
    skyblock.setzone:
      description: With this permission players can change the location of the island zone.
      default: op
