---
Version: 1

Spawn World: world

Generator Ores:
  #COBBLESTONE
  4: 60
  #COAL
  16: 8
  #LAPIS
  21: 8
  #REDSTONE
  73: 8
  #IRON
  15: 7
  #GOLD
  14: 4
  #DIAMOND
  56: 3
  #EMERALD
  129: 2


Starting Items:
  - 79, 0, 2
  - 325, 10, 1
  - 287, 0, 12
  - 351, 15, 2
  - 338, 0, 1
  - 361, 0, 1
  - 81, 0, 1
  - 360, 0, 1
  - 39, 0, 1
  - 40, 0, 1

Island Zone:
  0: 163
  1: 14
  2: 267
  3: 155
  4: 30
  5: 275

Zone World: world

Island Interval: 600

Island Size: 100

Island Spawn Y: 26
